# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network :forwarded_port, guest: 80, host: 3000, auto_correct: true
  config.vm.synced_folder "./", "/var/www", create: true, group: "web", owner: "web"

  config.vm.provision "shell" do |s|
    s.path = "provision/setup.sh"
  end
end
